apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
commonLabels:
  app.kubernetes.io/name: argocd-repo-server
  app.kubernetes.io/part-of: argocd
resources:
- rbac/rbac.yml
- service.yml
- networkpolicy.yml
- deployment.yml
