apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
commonLabels:
  app.kubernetes.io/name: keycloak
  app.kubernetes.io/part-of: keycloak
resources:
- configmap.yml
- secret.yml
- deployment.yml
- service.yml
- ingress.yml
- job.yml
