apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
commonLabels:
  app.kubernetes.io/name: vault
  app.kubernetes.io/part-of: vault
resources:
- injector-clusterrole.yaml
- injector-clusterrolebinding.yaml
- injector-serviceaccount.yaml
- server-clusterrolebinding.yaml
- server-discovery-role.yaml
- server-discovery-rolebinding.yaml
- server-serviceaccount.yaml
