apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app.kubernetes.io/name: node-exporter
  app.kubernetes.io/part-of: node-exporter
resources:
- daemonset.yml
- service.yml
- servicemonitor.yml