apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app.kubernetes.io/name: kube-state-metrics
  app.kubernetes.io/part-of: kube-state-metrics
resources:
- rbac/
- deployment.yml
- service.yml
- servicemonitor.yml