apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: opentelemetry-collector
  app.kubernetes.io/part-of: opentelemetry-collector
resources:
- serviceaccount.yml