apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: kap-elastic
  namespace: elastic-system
spec:
  version: 7.17.10
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kap-elastic
  namespace: elastic-system
spec:
  version: 7.17.10
  count: 1
  elasticsearchRef:
    name: kap-elastic