apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik.yml: |
    log:
      level: DEBUG
    accessLog: {}
    api:
      insecure: true
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    entrypoints:
      metrics:
        address: ":9100/tcp"
      traefik:
        address: ":9000/tcp"
      web:
        address: ":8000/tcp"
      websecure:
        address: ":8443/tcp"
    providers:
      kubernetesCRD:
        namespaces:
          - traefik
          - app-ingress
        allowCrossNamespace: true
        allowExternalNameServices: true
        ingressClass: traefik-ingress
    ping:
      entryPoint: traefik
    metrics:
      prometheus:
        entrypoint: metrics
        addRoutersLabels: true
        addServicesLabels: true
    tracing:
      serviceName: traefik-ingress
      jaeger:
        samplingServerURL: http://localhost:5778/samling
        localAgentHostPort: localhost:6831