apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: traefik-ingress-controller
  app.kubernetes.io/part-of: traefik-ingress-controller
resources:
- namespace.yml
- crds/
- rbac/
- ingress.yml
- ingressclass.yml
- defaultcertificate.yml
- configmap.yml
- service.yml
- deployment.yml
- dashboard.yml
- servicemonitor.yml
