apiVersion: v1
kind: Secret
metadata:
  name: ${APP_NAME}-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://${REPOSITORY}
  password: $PASSWORD
  username: $USERNAME
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: $APP_NAME
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/${APP_NAME}-credentials
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: ${PROJECT_NAME}_${APP_NAME}=registry.dev.local/${PROJECT_NAME}/${APP_NAME}
    argocd-image-updater.argoproj.io/${PROJECT_NAME}_${APP_NAME}.force-update: "true"
spec:
  project: $PROJECT_NAME
  source:
    repoURL: https://${REPOSITORY}
    targetRevision: HEAD
    path: $ARGO_PATH
  destination:
    server: https://kubernetes.default.svc
    namespace: $PROJECT_NAME
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    - PruneLast=true
