apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: $PROJECT_NAME
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for $PROJECT_NAME
  sourceRepos:
  - '*'
  destinations:
  - namespace: $PROJECT_NAME
    server: https://kubernetes.default.svc
    name: in-cluster
  - namespace: app-ingress
    server: https://kubernetes.default.svc
    name: app-ingress
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: StatefulSet
  - group: ''
    kind: Service
  - group: 'traefik.containo.us'
    kind: Middleware
  - group: 'traefik.containo.us'
    kind: IngressRoute
  orphanedResources:
    warn: false
