apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app.kubernetes.io/name: prometheus-operator
  app.kubernetes.io/part-of: prometheus
resources:
- alertmanager.yml
- alertmanagerconfig.yml
- podmonitor.yml
- probe.yml
- prometheus.yml
- prometheusrule.yml
- servicemonitor.yml
- thanosruler.yml