apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
commonLabels:
  app.kubernetes.io/name: vault
  app.kubernetes.io/part-of: vault
resources:
- rbac
- injector-deployment.yaml
- injector-mutating-webhook.yaml
- injector-service.yaml
- server-config-configmap.yaml
- server-disruptionbudget.yaml
- server-ha-active-service.yaml
- server-ha-standby-service.yaml
- server-headless-service.yaml
- server-service.yaml
- server-statefulset.yaml
- ui-service.yaml
- server-ingress.yaml
