---
# Source: vault/templates/server-config-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
  labels:
    helm.sh/chart: vault-0.23.0
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
data:
  extraconfig-from-values.hcl: |-
    disable_mlock = true
    ui = true
    listener "tcp" {
      address = "[::]:8200"
      cluster_address = "[::]:8201"
      tls_cert_file = "/vault/userconfig/vault-secret/tls.crt"
      tls_key_file = "/vault/userconfig/vault-secret/tls.key"
      tls_client_ca_file = "/vault/userconfig/vault-secret/ca.crt"
    }

    storage "consul" {
      address = "consul-consul-server-0.consul-consul-server.vault:8500"
      path = "vault/"
    }

    service_registration "kubernetes" {}
