---
# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-6.48.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "9.3.1"
    app.kubernetes.io/managed-by: Helm
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = chart-example.local
  datasources.yml: |
    apiVersion: 1
    datasources:
    - name: Main
      type: prometheus
      url: http://prometheus-operated.monitoring:9090
      isDefault: false
      jsonData:
        manageAlerts: false
  dashboardproviders.yml: |
    apiVersion: 1
    providers:
    - disableDeletion: false
      editable: false
      folder: Nginx
      name: nginx
      options:
        path: /var/lib/grafana/dashboards/nginx
      orgId: 1
      type: file
    - disableDeletion: false
      editable: false
      folder: Kubernetes
      name: kubernetes
      options:
        path: /var/lib/grafana/dashboards/kubernetes
      orgId: 1
      type: file
    - disableDeletion: false
      editable: false
      folder: Jenkins
      name: jenkins
      options:
        path: /var/lib/grafana/dashboards/jenkins
      orgId: 1
      type: file
    - disableDeletion: false
      editable: false
      folder: SonarQube
      name: sonarqube
      options:
        path: /var/lib/grafana/dashboards/sonarqube
      orgId: 1
      type: file