apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/part-of: grafana
resources:
- rbac/
- dashboards/
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml