---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- ingressroute.yml
replacements:
- source:
    name: ${APP_NAME}
    kind: Deployment
    fieldPath: spec.template.spec.containers.[name=app].image
    options:
      delimiter: ":"
      index: 1
      create: true
  targets:
  - select:
      name: ${APP_NAME}
      kind: Deployment
    fieldPaths:
    - spec.template.spec.containers.[name=app].env.[name=APP_VERSION].value
...
