apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: monitoring
  labels:
    app: fluentbit
    release: fluentbit
spec:
  selector:
    matchLabels:
      app: fluentbit
      release: fluentbit
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: fluentbit
        release: fluentbit
    spec:
      serviceAccountName: fluentbit
      hostNetwork: false
      dnsPolicy: ClusterFirst
      containers:
      - name: fluentbit
        image: cr.fluentbit.io/fluent/fluent-bit:2.1.4
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 2020
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: http
        volumeMounts:
        - mountPath: /fluent-bit/etc/fluent-bit.conf
          name: config
          subPath: fluent-bit.conf
        - mountPath: /fluent-bit/etc/custom_parsers.conf
          name: config
          subPath: custom_parsers.conf
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /etc/machine-id
          name: etcmachineid
          readOnly: true
        - mountPath: /fluent-bit/ssl/kap-elastic-ca.crt
          name: elastic-ca-certificate
          subPath: ca.crt
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: fluentbit-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: etcmachineid
        hostPath:
          path: /etc/machine-id
          type: File
      - name: elastic-ca-certificate
        secret:
          secretName: kap-elastic-ca
