apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: fluentbit
  app.kubernetes.io/part-of: fluentbit
resources:
- rbac
- daemonset.yml
- service.yml
