apiVersion: v1
kind: Service
metadata:
  name: fluentbit
  namespace: monitoring
  labels:
    app: fluentbit
    release: fluentbit
spec:
  type: ClusterIP
  ports:
  - port: 2020
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: fluentbit
    release: fluentbit
