apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-kap
  namespace: jaeger
  labels:
    app: jaeger-kap
spec:
  strategy: production
  ui:
    options:
      monitor:
        menuEnabled: true
  collector:
    maxReplicas: 5
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  query:
    metricsStorage:
      type: prometheus
    options:
      prometheus:
        server-url: http://prometheus-operated.monitoring.svc:9090
  storage:
      type: elasticsearch
      options:
        es:
          server-urls: https://kap-elastic-es-http.elastic-system.svc:9200
          index-prefix: kap_
          version: 7
          # create-index-templates: false
          tls:
            ca: /es/certificates/ca.crt
      secretName: jaeger-es-secret
  ingress:
    enabled: false
  volumeMounts:
  - name: certificates
    mountPath: /es/certificates
    readOnly: true
  volumes:
  - name: certificates
    secret:
      secretName: jaeger-es-http-certs-public