apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  app.kubernetes.io/name: metrics-server
  app.kubernetes.io/part-of: metrics-server
resources:
- rbac/rbac.yml
- service.yml
- deployment.yml
- apiservice.yml
