apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-postgresql-init-db
  namespace: keycloak
  labels:
    app: keycloak
    release: keycloak
data:
  init_revision.sh: |
    if [[ ! -f "$POSTGRESQL_VOLUME_DIR/.keycloak_1_scripts_initilized" ]] ; then
      rm -f "$POSTGRESQL_VOLUME_DIR/.user_scripts_initialized"
      touch "$POSTGRESQL_VOLUME_DIR/.keycloak_1_scripts_initialized"
    fi
