apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
commonLabels:
  app.kubernetes.io/name: keycloak
  app.kubernetes.io/part-of: keycloak
resources:
- secret.yml
- configmap.yml
- statefulset.yml
- service.yml
