apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgresql-headless
  namespace: keycloak
  labels:
    app: keycloak
    release: keycloak
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app: postgresql
    release: keycloak
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgresql
  namespace: keycloak
  labels:
    app: postgresql
    release: keycloak
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app: postgresql
    release: keycloak
    role: master
