apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-traefik
  namespace: traefik
  labels:
    app: jaeger-traefik
spec:
  strategy: production
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  storage:
      type: elasticsearch
      options:
        es:
          server-urls: https://kap-elastic-es-http.elastic-system.svc:9200
          index-prefix: traefik
          version: 7
          create-index-templates: false
          tls:
            ca: /es/certificates/ca.crt
      secretName: jaeger-es-secret
  ingress:
    enabled: false
  volumeMounts:
  - name: certificates
    mountPath: /es/certificates
    readOnly: true
  volumes:
  - name: certificates
    secret:
      secretName: jaeger-es-http-certs-public