apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- namespace.yml
- prometheus-operator/
- prometheus/
- kube-state-metrics/
- kube-exporters/
- node-exporter/
- cadvisor/
- grafana/