apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab
commonLabels:
  app.kubernetes.io/name: minio
  app.kubernetes.io/part-of: gitlab
resources:
- configmap.yaml
- deployment.yaml
- kustomization.yml
- role-binding.yaml
- role.yaml
- service-account.yaml
