apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab
commonLabels:
  app.kubernetes.io/name: redis
  app.kubernetes.io/part-of: gitlab
resources:
- configmap.yaml
- headless-svc.yaml
- health-configmap.yaml
- kustomization.yml
- metrics-svc.yaml
- redis-master-statefulset.yaml
- redis-master-svc.yaml
