apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
commonLabels:
  app.kubernetes.io/name: argocd-image-updater
  app.kubernetes.io/part-of: argocd-image-updater
resources:
- serviceaccount.yml
- role.yml
- rolebinding.yml
