---
# Source: gitlab/charts/certmanager-issuer/templates/rbac-config.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-certmanager-issuer
  namespace: gitlab
  labels:
    app: certmanager-issuer
    chart: certmanager-issuer-0.1.0
    release: gitlab
    heritage: Helm
    
  annotations:
    namespace: gitlab
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-certmanager-issuer
  namespace: gitlab
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["issuers", "clusterissuers", "certificates"]
  verbs: ["get", "list", "update", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-certmanager-issuer
  namespace: gitlab
  labels:
    app: certmanager-issuer
    chart: certmanager-issuer-0.1.0
    release: gitlab
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-certmanager-issuer
subjects:
  - kind: ServiceAccount
    name: gitlab-certmanager-issuer
    namespace: gitlab
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-certmanager-clusterissuer
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["clusterissuers"]
  verbs: ["get", "list", "update", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-certmanager-clusterissuer
  labels:
    app: certmanager-issuer
    chart: certmanager-issuer-0.1.0
    release: gitlab
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab-certmanager-clusterissuer
subjects:
- kind: ServiceAccount
  name: gitlab-certmanager-issuer
  namespace: gitlab
