---
# Source: traefik/templates/ingressclass.yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: "false"
  labels:
    app.kubernetes.io/name: gitlab-nginx
  name: gitlab-nginx
  namespace: gitlab
spec:
  controller: k8s.io/ingress-nginx 
