apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab
commonLabels:
  app.kubernetes.io/name: prometheus
  app.kubernetes.io/part-of: gitlab
resources:
- clusterrolebinding.yaml
- cm.yaml
- deploy.yaml
- pvc.yaml
- service.yaml
- serviceaccount.yaml
