apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-change-admin-password
  namespace: argocd
  labels:
    app: argocd
    release: argocd
    role: change-admin-password
spec:
  template:
    metadata:
      labels:
        app: argocd
        release: argocd
        role: change-admin-password
    spec:
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: wait-for-argocd-server
        image: curlimages/curl:8.1.0
        command: ["sh", "-c"]
        args:
          - |
            until curl -s --cacert /tmp/argocd-ca.crt "https://argocd.dev.local/api/version" | grep -q -e '"Version":'; do sleep 10; done
        volumeMounts:
        - mountPath: /tmp/argocd-ca.crt
          subPath: argocd-ca.crt
          name: argocd-ca
      - name: change-admin-password
        image: quay.io/argoproj/argocd:v2.5.4
        command: ["bash", "-c"]
        args:
          - |
            ARGOCD_HOST="argocd.dev.local"
            argocd login ${ARGOCD_HOST} --username admin --password $ARGOCD_INITIAL_ADMIN_PASSWORD
            argocd account update-password --server ${ARGOCD_HOST} --current-password ${ARGOCD_INITIAL_ADMIN_PASSWORD} --new-password ${ARGOCD_ADMIN_PASSWORD} --account ${ARGOCD_ADMIN_USERNAME}
        env:
        - name: ARGOCD_INITIAL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: argocd-initial-admin-secret
              key: password
        - name: ARGOCD_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: argocd-admin-user
              key: username
        - name: ARGOCD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: argocd-admin-user
              key: password
        volumeMounts:
        - mountPath: /etc/ssl/certs/argocd-ca.crt
          subPath: argocd-ca.crt
          name: argocd-ca
      containers:
      - name: finish
        image: busybox:1.32
        command: ["sh", "-c", "echo ArgoCD admin password has been updated."]
      volumes:
      - name: argocd-ca
        secret:
          secretName: argocd-cert
          items:
          - key: ca.crt
            path: argocd-ca.crt