apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab
commonLabels:
  app.kubernetes.io/name: minio
  app.kubernetes.io/part-of: gitlab
resources:
- minioconfig_configmap.yaml
- minio_pvc.yaml
- minio_svc.yaml
- ingress.yaml
- minio_deployment.yaml
- pdb.yaml
- create-buckets-job.yaml