apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-config
  namespace: sonarqube
data:
  sonar.properties: |
    sonar.es.bootstrap.checks.disable=true
    sonar.web.javaOpts=-javaagent:/opt/sonarqube/data/jmx_prometheus_javaagent.jar=8000:/opt/sonarqube/conf/prometheus-config.yaml -Djavax.net.ssl.trustStore=/opt/sonarqube/certs/cacerts
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-database-config
  namespace: sonarqube
data:
  SONAR_JDBC_USERNAME: sonarUser
  SONAR_JDBC_DATABASE: sonarDB
  SONARQUBE_POSTGRESQL_HOST: sonarqube-postgresql.sonarqube.svc
  SONAR_JDBC_URL: "jdbc:postgresql://sonarqube-postgresql.sonarqube.svc:5432/sonarDB?socketTimeout=1500"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-init-sysctl
  namespace: sonarqube
data:
  init_sysctl.sh: |-
    if [[ "$(sysctl -n vm.max_map_count)" -lt 524288 ]]; then
      sysctl -w vm.max_map_count=524288
    fi
    if [[ "$(sysctl -n fs.file-max)" -lt 131072 ]]; then
      sysctl -w fs.file-max=131072
    fi
    if [[ "$(ulimit -n)" != "unlimited" ]]; then
      if [[ "$(ulimit -n)" -lt 131072 ]]; then
        echo "ulimit -n 131072"
        ulimit -n 131072
      fi
    fi
    if [[ "$(ulimit -u)" != "unlimited" ]]; then
      if [[ "$(ulimit -u)" -lt 8192 ]]; then
        echo "ulimit -u 8192"
        ulimit -u 8192
      fi
    fi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-init-fs
  namespace: sonarqube
data:
  init_fs.sh: |-

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-install-plugins
  namespace: sonarqube
data:
  install_plugins: |-
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-prometheus-config
  namespace: sonarqube
  labels:
    app: sonarqube
    release: sonarqube
data:
  prometheus-config.yaml: |-
    rules:
      - pattern: ".*"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-prometheus-ce-config
  namespace: sonarqube
  labels:
    app: sonarqube
    release: sonarqube
data:
  prometheus-ce-config.yaml: |-
    rules:
      - pattern: ".*"