apiVersion: batch/v1
kind: Job
metadata:
  name: sonarqube-init
  namespace: sonarqube
  labels:
    app: sonarqube
    release: sonarqube
    role: init-job
spec:
  template:
    metadata:
      labels:
        app: sonarqube
        release: sonarqube
        role: init-job
    spec:
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: sonarqube-change-default-admin-password
        image: curlimages/curl:8.1.0
        command: ["sh", "-c"]
        args:
          - |
            until curl -v --connect-timeout 100 "sonarqube:9000/api/system/status" | grep -q -e '"status":"UP"' -e '"status":"DB_MIGRATION_NEEDED"' -e '"status":"DB_MIGRATION_RUNNING"'; do sleep 10; done
            curl -v --connect-timeout 100 -u admin:$CURRENT_ADMIN_PASSWORD -X POST "sonarqube:9000/api/users/change_password?login=admin&previousPassword=$CURRENT_ADMIN_PASSWORD&password=$ADMIN_PASSWORD"
        env:
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarqube-admin-password
              key: password
        - name: CURRENT_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarqube-admin-password
              key: currentPassword
      - name: sonarqube-add-gitlab-integration
        image: curlimages/curl:8.1.0
        command: ["sh", "-c"]
        args:
          - |
            until curl -v --connect-timeout 100 "sonarqube:9000/api/system/status" | grep -q -e '"status":"UP"' -e '"status":"DB_MIGRATION_NEEDED"' -e '"status":"DB_MIGRATION_RUNNING"'; do sleep 10; done
            GITLAB_HOST="gitlab.dev.local"
            echo GITLAB_HOST: $GITLAB_HOST
            GITLAB_AUTH_TOKEN=$(curl --cacert /tmp/gitlab-ca.crt -s -X POST -H "Content-Type: application/json" \
                                    -d "{\"grant_type\":\"password\",\"username\":\"${GITLAB_ADMIN_USERNAME}\",\"password\":\"${GITLAB_ADMIN_PASSWORD}\"}" \
                                    "https://${GITLAB_HOST}/oauth/token" | sed -E 's/.*"access_token":"?([^,"]*)"?.*/\1/')
            echo GITLAB_AUTH_TOKEN: $GITLAB_AUTH_TOKEN
            GITLAB_AUTH_HEADER="Authorization: Bearer $GITLAB_AUTH_TOKEN"
            echo GITLAB_AUTH_HEADER: $GITLAB_AUTH_HEADER
            GITLAB_PERSONAL_ACCESS_TOKEN=$(curl --cacert /tmp/gitlab-ca.crt -s -X POST -H "Content-Type: application/json" -H "${GITLAB_AUTH_HEADER}" \
                                    -d "{ \"name\":\"SonarQube\", \"scopes\":[\"api\"], \"expires_at\":\"2026-01-31\" }" \
                                    "https://${GITLAB_HOST}/api/v4/users/1/personal_access_tokens" | sed -E 's/.*"token":"?([^,"]*)"?.*/\1/')
            echo GITLAB_PERSONAL_ACCESS_TOKEN: $GITLAB_PERSONAL_ACCESS_TOKEN
            curl -v --connect-timeout 100 -u admin:$ADMIN_PASSWORD -X POST "sonarqube:9000/api/alm_settings/create_gitlab?key=gitlab-dev-local&personalAccessToken=${GITLAB_PERSONAL_ACCESS_TOKEN}&url=https://${GITLAB_HOST}/api/v4"
            SONARQUBE_TOKEN=$(curl -s --connect-timeout 100 -u admin:$ADMIN_PASSWORD -X POST \
                                    "sonarqube:9000/api/user_tokens/generate?name=gitlab-dev-local&type=USER_TOKEN&login=admin" | sed -E 's/.*"token":"?([^,"]*)"?.*/\1/')
            echo SONARQUBE_TOKEN: $SONARQUBE_TOKEN
            curl --cacert /tmp/gitlab-ca.crt -s -X POST -H "Content-Type: application/json" -H "${GITLAB_AUTH_HEADER}" \
                -d "{\"key\":\"SONAR_HOST_URL\",\"value\":\"sonarqube.dev.local\",\"variable_type\":\"env_var\",\"protected\":true,\"masked\":true}" \
                "https://${GITLAB_HOST}/api/v4/admin/ci/variables"
            curl --cacert /tmp/gitlab-ca.crt -s -X POST -H "Content-Type: application/json" -H "${GITLAB_AUTH_HEADER}" \
                -d "{\"key\":\"SONAR_TOKEN\",\"value\":\"${SONARQUBE_TOKEN}\",\"variable_type\":\"env_var\",\"protected\":true,\"masked\":true}" \
                "https://${GITLAB_HOST}/api/v4/admin/ci/variables"
        env:
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarqube-admin-password
              key: password
        - name: GITLAB_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: gitlab-admin-user
              key: username
        - name: GITLAB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-admin-user
              key: password
        volumeMounts:
        - mountPath: /tmp/gitlab-ca.crt
          subPath: gitlab-ca.crt
          name: gitlab-ca
      - name: get-keycloak-realm-certificate
        image: curlimages/curl:8.1.0
        command: ["sh", "-c"]
        args:
          - |
            curl -s "keycloak.keycloak.svc:8080/realms/kap/protocol/saml/descriptor" | sed -nE 's/.*<ds:X509Certificate>(.*)<\/ds:X509Certificate>.*/\1/p' | tr -d '\n' > /tmp/keycloak/kap.crt
        volumeMounts:
        - name: keycloak-realm-certificate
          mountPath: /tmp/keycloak
      - name: add-saml-config-to-db
        image: docker.io/bitnami/postgresql:12.7.0
        command: ["sh", "-c"]
        args:
          - |
            KEYCLOAK_REALM_CERTIFICATE=$(cat /tmp/keycloak/kap.crt)
            CREATED_AT=$(date +%s%N | cut -b1-13)
            INSERT_SQL="
              INSERT INTO
                properties (uuid, prop_key, created_at, is_empty, text_value)
              VALUES
                ('"$(cat /proc/sys/kernel/random/uuid)"', 'sonar.core.serverBaseURL',             $CREATED_AT, false, 'https://sonarqube.dev.local'),
                ('"$(cat /proc/sys/kernel/random/uuid)"', 'sonar.auth.saml.enabled',              $CREATED_AT, false, 'true'),
                ('"$(cat /proc/sys/kernel/random/uuid)"', 'sonar.auth.saml.applicationId',        $CREATED_AT, false, 'sonarqube'),
                ('"$(cat /proc/sys/kernel/random/uuid)"', 'sonar.auth.saml.providerName',         $CREATED_AT, false, 'SAML'),
                ('"$(cat /proc/sys/kernel/random/uuid)"', 'sonar.auth.saml.providerId',           $CREATED_AT, false, 'https://keycloak.dev.local/realms/kap'),
                ('"$(cat /proc/sys/kernel/random/uuid)"', 'sonar.auth.saml.loginUrl',             $CREATED_AT, false, 'https://keycloak.dev.local/realms/kap/protocol/saml/clients/sonarqube'),
                ('"$(cat /proc/sys/kernel/random/uuid)"', 'sonar.auth.saml.user.login',           $CREATED_AT, false, 'login'),
                ('"$(cat /proc/sys/kernel/random/uuid)"', 'sonar.auth.saml.user.name',            $CREATED_AT, false, 'name'),
                ('"$(cat /proc/sys/kernel/random/uuid)"', 'sonar.auth.saml.user.email',           $CREATED_AT, false, 'email'),
                ('"$(cat /proc/sys/kernel/random/uuid)"', 'sonar.auth.saml.group.name',           $CREATED_AT, false, 'groups'),
                ('"$(cat /proc/sys/kernel/random/uuid)"', 'sonar.auth.saml.certificate.secured',  $CREATED_AT, false, '"${KEYCLOAK_REALM_CERTIFICATE}"'),
                ('"$(cat /proc/sys/kernel/random/uuid)"', 'sonar.auth.saml.signature.enabled',    $CREATED_AT, false, 'false');
            "
            psql -c "$INSERT_SQL"
        env:
        - name: PGHOST
          valueFrom:
            configMapKeyRef:
              name: sonarqube-database-config
              key: SONARQUBE_POSTGRESQL_HOST
        - name: PGUSER
          valueFrom:
            configMapKeyRef:
              name: sonarqube-database-config
              key: SONAR_JDBC_USERNAME
        - name: PGDATABASE
          valueFrom:
            configMapKeyRef:
              name: sonarqube-database-config
              key: SONAR_JDBC_DATABASE
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarqube-database
              key: jdbc-password
        volumeMounts:
        - name: keycloak-realm-certificate
          mountPath: /tmp/keycloak
      containers:
      - name: finish
        image: busybox:1.32
        command: ["sh", "-c", "echo SonarQube init finished."]
      volumes:
      - name: gitlab-ca
        secret:
          secretName: gitlab-ca-cert
          items:
          - key: gitlab-dev-local
            path: gitlab-ca.crt
      - name: keycloak-realm-certificate
        emptyDir:
          medium: Memory
          sizeLimit: 10Mi