apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-database
  namespace: sonarqube
type: Opaque
data:
  jdbc-password: c29uYXJxdWJlCg==  # sonarqube
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-monitoring-passcode
  namespace: sonarqube
type: Opaque
data:
  SONAR_WEB_SYSTEMPASSCODE: c29uYXJxdWJlCg==  # sonarqube