apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-database
  namespace: sonarqube
type: Opaque
data:
  jdbc-password: c29uYXJxdWJl  # sonarqube
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-admin-password
  namespace: sonarqube
data:
  password: c29uYXI=  # sonar
  currentPassword: YWRtaW4=  # admin
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-monitoring-passcode
  namespace: sonarqube
type: Opaque
data:
  SONAR_WEB_SYSTEMPASSCODE: c29uYXJxdWJl  # sonarqube
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-monitoring-basicauth
  namespace: monitoring
type: Opaque
data:
  user: YWRtaW4=      # admin
  password: c29uYXI=  # sonar