apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
commonLabels:
  app.kubernetes.io/name: ingress-nginx-controller
  app.kubernetes.io/part-of: ingress-nginx
resources:
- rbac/rbac.yml
- service.yml
- deployment.yml
- apiservice.yml
