apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app.kubernetes.io/name: cadvisor
  app.kubernetes.io/part-of: cadvisor
resources:
- rbac/
- daemonset.yml
- service.yml
- servicemonitor.yml
- ingress.yml