apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
commonLabels:
  app.kubernetes.io/name: argocd
  app.kubernetes.io/part-of: argocd
resources:
- namespace.yml
- crds/crds.yml
- rbac/rbac.yml
- configmap.yml
- service.yml
- deployment.yml
- statefulset.yml
- networkpolicy.yml
- ingress.yml
