apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
commonLabels:
  app.kubernetes.io/name: argocd
  app.kubernetes.io/part-of: argocd
resources:
- crds/crds.yml
- rbac/rbac.yml
- namespace.yml
- configmap.yml
- argocd-redis
- argocd-repo-server
- argocd-notifications-controller
- argocd-applicationset-controller
- argocd-application-controller
- argocd-server