apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app.kubernetes.io/name: prometheus-operated
  app.kubernetes.io/part-of: prometheus
resources:
- rbac/
- prometheus.yml
- ingress.yml