apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: jenkins
data:
  JENKINS_HOME: "/var/jenkins_home/"
  JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
  CASC_JENKINS_CONFIG: "/usr/share/jenkins/ref/casc.yml"
  plugins: |
    github-branch-source:1701.v00cc8184df93
    workflow-aggregator:596.v8c21c963d92d
    configuration-as-code:1625.v27444588cc3d
    cloudbees-disk-usage-simple:182.v62ca_0c992a_f3
    kubernetes:3893.v73d36f3b_9103
    opentelemetry:2.13.0
    prometheus:2.1.1
  casc: |
    jenkins:
      systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
      securityRealm:
        local:
          allowsSignup: false
          users:
            - id: "admin"
              password: "admin"
              name: "Admin"
              description: "Admin"
      authorizationStrategy: loggedInUsersCanDoAnything
      clouds:
      - kubernetes:
          name: kubernetes
          jenkinsUrl: "http://jenkins:8080/"
          jenkinsTunnel: "jenkins:50000"
          containerCapStr: 42
          maxRequestsPerHostStr: 64
          retentionTimeout: 5
          connectTimeout: 10
          readTimeout: 20
          templates:
            - name: maven
              label: mavenpodtemplate
              containers:
              - name: maven
                image: maven:3.3.9-jdk-8-alpine
                ttyEnabled: true
                command: cat
                args: ""
    unclassified:
      location:
        url: http://jenkins:8080/
