apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
        app.kubernetes.io/name: jenkins
        app.kubernetes.io/part-of: jenkins
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      serviceAccountName: jenkins
      initContainers:
      - name: install-plugins
        image: jenkins/jenkins:lts
        command: ["/bin/jenkins-plugin-cli"]
        args: ["--plugin-file", "/usr/share/jenkins/ref/plugins.txt", "--plugin-download-directory", "/var/jenkins_home/plugins", "--verbose"]
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: jenkins-config
          mountPath: /usr/share/jenkins/ref
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        resources:
          limits:
            memory: "2Gi"
            cpu: "2000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 8080
        - name: jnlp
          containerPort: 50000
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: jenkins-config
          mountPath: /usr/share/jenkins/ref
        livenessProbe:
          httpGet:
            path: "/login"
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: "/login"
            port: 8080
          initialDelaySeconds: 360
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: JENKINS_HOME
          valueFrom:
            configMapKeyRef:
              name: jenkins-config
              key: JENKINS_HOME
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: jenkins-config
              key: JAVA_OPTS
        - name: CASC_JENKINS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: jenkins-config
              key: CASC_JENKINS_CONFIG
      volumes:
      - name: jenkins-home
        emptyDir: {}
      - name: jenkins-config
        configMap:
          name: jenkins-config
          items:
          - key: plugins
            path: plugins.txt
          - key: casc
            path: casc.yml