apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-http
  namespace: jenkins
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: kap-vault-issuer
    cert-manager.io/common-name: jenkins.dev.local
spec:
  ingressClassName: nginx
  rules:
  - host: jenkins.dev.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080
  tls:
  - hosts:
    - jenkins.dev.local
    secretName: jenkins-cert