apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins
commonLabels:
  app.kubernetes.io/name: jenkins
  app.kubernetes.io/part-of: jenkins
resources:
- namespace.yml
- rbac/serviceaccount.yml
- service.yml
- deployment.yml
- ingress.yml
