apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: jenkins
  app.kubernetes.io/part-of: jenkins
resources:
- namespace.yml
- configmap.yml
- rbac/serviceaccount.yml
- service.yml
- servicemonitor.yml
- deployment.yml
- ingress.yml
