apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins-controller-metrics
  namespace: monitoring
  labels:
    app: jenkins-controller-metrics
    prometheus: monitoring
spec:
  endpoints:
  - port: http
    path: /prometheus
  namespaceSelector:
    matchNames:
    - jenkins
  selector:
    matchLabels:
      app: jenkins-controller-metrics