apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-ss-issuer
  namespace: vault
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-ss-ca
  namespace: vault
spec:
  isCA: true
  commonName: vault-ss-ca
  secretName: vault-ss-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: vault-ss-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-ss-ca-issuer
  namespace: vault
spec:
  ca:
    secretName: vault-ss-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-ss-cert
  namespace: vault
spec:
  isCA: false
  commonName: vault.vault
  secretName: vault-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - vault-0.vault-internal
    - vault-1.vault-internal
    - vault-2.vault-internal
    - vault.vault
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: vault-ss-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: consul-ss-cert
  namespace: vault
spec:
  isCA: false
  commonName: consul.dev.local
  secretName: consul-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: vault-ss-ca-issuer
    kind: Issuer
    group: cert-manager.io
