apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-selfsigned-ca
  namespace: vault
spec:
  isCA: true
  commonName: dev.local
  secretName: vault-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: kap-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: vault
  labels:
    app: certmanager-issuer
    chart: certmanager-issuer-0.1.0
    release: vault
    heritage: Helm
spec:
  ca:
    secretName: vault-ca-secret
