apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kuberentes.io/name: argocd-image-updater-config
  name: argocd-image-updater-config
data:
  log.level: debug
  registries.conf: |
    registries:
    - name: GitLab Container Registry
      prefix: registry.dev.local
      api_url: https://registry.dev.local
      credentials: pullsecret:argocd/gitlab-registry-creds
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-ssh-config
  name: argocd-image-updater-ssh-config
