apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
commonLabels:
  app.kubernetes.io/part-of: argocd-image-updater
resources:
- rbac/
- secret.yml
- configmap.yml
- deployment.yml