apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-repo
  namespace: test-group
  labels:
    app: test-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-repo
  template:
    metadata:
      labels:
        app: test-repo
    spec:
      containers:
        - name: app
          image: registry.dev.local/test-group/test-repo:latest
          ports:
          - containerPort: 8090
            protocol: TCP
            name: web
      imagePullSecrets:
      - name: test-repo-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: test-repo
  namespace: app-ingress
spec:
  selector:
    app: test-repo
  ports:
  - name: web
    port: 8090
    protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-repo
  namespace: app-ingress
spec:
  stripPrefix:
    prefixes:
      - "/test-repo"
    forceSlash: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: test-repo
  namespace: app-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik-ingress"
spec:
  entryPoints:
  - websecure
  routes:
    - kind: Rule
      match: PathPrefix(`/test-repo`)
      middlewares:
      - name: test-repo
        namespace: app-ingress
      services:
      - name: test-repo
        namespace: app-ingress
        port: web
  tls: {}
