apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
  namespace: service-1
  labels:
    app: project-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-one
  spec:
    metadata:
      labels:
        app: project-one
    spec:
      containers:
        - name: app
          image: registry.dev.local/project-one:1.0.0
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: service-1
  namespace: service-1
spec:
  selector:
    app: project-one
  ports:
  - name: web
    port: 8090
    protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: service-1
  namespace: service-1
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/service-1`)
      services:
      - kind: Service
        name: service-1
        namespace: service-1
