apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
  namespace: service-1
  labels:
    app: project-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-one
  template:
    metadata:
      labels:
        app: project-one
    spec:
      containers:
        - name: app
          image: registry.dev.local/project-one/project-one:latest
          ports:
          - containerPort: 8090
            protocol: TCP
            name: web
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: service-1
  namespace: service-1
spec:
  selector:
    app: project-one
  ports:
  - name: web
    port: 8090
    protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: service-1
  namespace: service-1
spec:
  stripPrefix:
    prefixes:
      - "/service-1"
    forceSlash: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: service-1
  namespace: service-1
  annotations:
    kubernetes.io/ingress.class: "traefik-ingress"
spec:
  entryPoints:
  - websecure
  routes:
    - kind: Rule
      match: PathPrefix(`/service-1`)
      middlewares:
      - name: service-1
        namespace: service-1
      services:
      - name: service-1
        namespace: service-1
        port: web
  tls: {}
