apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
commonLabels:
  app.kubernetes.io/name: traefik-ingress-controller
  app.kubernetes.io/part-of: traefik-ingress-controller
resources:
  - clusterrole.yml
  - clusterrolebinding.yml
  - role.yml
  - rolebinding.yml
  - serviceaccount.yml
