apiVersion: batch/v1
kind: Job
metadata:
  name: gitlab-create-admin-user
  namespace: gitlab
  labels:
    app: gitlab
    release: gitlab
    role: create-admin-user
spec:
  template:
    metadata:
      labels:
        app: gitlab
        release: gitlab
        role: create-admin-user
    spec:
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 1000
      containers:
      - name: create-admin-user
        image: curlimages/curl:8.1.0
        command: ["sh", "-c"]
        args:
        - |
          GITLAB_HOST="gitlab.dev.local"
          until curl --cacert /tmp/gitlab-ca.crt --connect-timeout 100 "https://${GITLAB_HOST}/-/readiness" | grep -q -e '"status":"ok"'; do sleep 10; done
          GITLAB_AUTH_TOKEN=$(curl --cacert /tmp/gitlab-ca.crt -s -X POST -H "Content-Type: application/json" \
                                -d "{\"grant_type\":\"password\",\"username\":\"root\",\"password\":\"${GITLAB_ROOT_PASSWORD}\"}" \
                                "https://${GITLAB_HOST}/oauth/token" | sed -E 's/.*"access_token":"?([^,"]*)"?.*/\1/')
          GITLAB_AUTH_HEADER="Authorization: Bearer $GITLAB_AUTH_TOKEN"
          curl --cacert /tmp/gitlab-ca.crt -v -X POST -H "Content-Type: application/json" -H "$GITLAB_AUTH_HEADER" \
              -d "{\"admin\":true,\"email\":\"gitlab@dev.local\",\"name\":\"${GITLAB_ADMIN_USERNAME}\",\"password\":\"${GITLAB_ADMIN_PASSWORD}\",\"username\":\"${GITLAB_ADMIN_USERNAME}\",\"skip_confirmation\":true,\"force_random_password\":false,\"reset_password\":false}" \
              "https://${GITLAB_HOST}/api/v4/users"
        env:
        - name: GITLAB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-gitlab-initial-root-password
              key: password
        - name: GITLAB_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: gitlab-admin-user
              key: username
        - name: GITLAB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-admin-user
              key: password
        volumeMounts:
        - mountPath: /tmp/gitlab-ca.crt
          subPath: gitlab-ca.crt
          name: gitlab-ca
      volumes:
      - name: gitlab-ca
        secret:
          secretName: gitlab-ca-secret
          items:
          - key: ca.crt
            path: gitlab-ca.crt