apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: ingress-nginx-controller
  app.kubernetes.io/part-of: ingress-nginx
resources:
- namespace.yml
- rbac/rbac.yml
- configmap.yml
- ingressclass.yaml
- service.yml
- servicemonitor.yml
- deployment.yml
- job.yml
- webhook.yml
