apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portainer
commonLabels:
  app.kubernetes.io/name: portainer
  app.kubernetes.io/part-of: portainer
resources:
- namespace.yml
- rbac/rbac.yml
- volume.yml
- service.yml
- ingress.yml
- deployment.yml
