apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
commonLabels:
  app.kubernetes.io/name: argocd-application-controller
  app.kubernetes.io/part-of: argocd
resources:
- rbac/rbac.yml
- networkpolicy.yml
- service.yml
- statefulset.yml
