###
###   Cert-Manager Certificate does not currently support "basic constraint: CA:TRUE"
###

# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: gitlab-selfsigned-ca
#   namespace: gitlab
# spec:
#   isCA: true
#   commonName: dev.local
#   secretName: gitlab-ca-secret
#   duration: 2160h # 90 days
#   renewBefore: 360h # 15 days
#   privateKey:
#     algorithm: ECDSA
#     size: 256
#   issuerRef:
#     name: kap-vault-issuer
#     kind: ClusterIssuer
#     group: cert-manager.io
# ---
# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#   name: gitlab-issuer
#   namespace: gitlab
#   labels:
#     app: certmanager-issuer
#     chart: certmanager-issuer-0.1.0
#     release: gitlab
#     heritage: Helm
# spec:
#   ca:
#     secretName: gitlab-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: gitlab-ss-issuer
  namespace: gitlab
  labels:
    app: certmanager-issuer
    chart: certmanager-issuer-0.1.0
    release: gitlab
    heritage: Helm
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-ss-ca
  namespace: gitlab
spec:
  isCA: true
  commonName: dev.local
  secretName: gitlab-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: gitlab-ss-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: gitlab-issuer
  namespace: gitlab
spec:
  ca:
    secretName: gitlab-ca-secret