---
# Source: consul/templates/connect-inject-leader-election-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: consul-consul-connect-inject-leader-election
  namespace: vault
  labels:
    app: consul
    chart: consul-helm
    heritage: Helm
    release: consul
    component: connect-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: consul-consul-connect-inject-leader-election
subjects:
- kind: ServiceAccount
  name: consul-consul-connect-injector
  namespace: vault
