---
# Source: gitlab/charts/certmanager-issuer/templates/cert-manager.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-certmanager-issuer-certmanager
  namespace: gitlab
  labels:
    app: certmanager-issuer
    chart: certmanager-issuer-0.1.0
    release: gitlab
    heritage: Helm
    
data:
  create-issuer: |
    #!/bin/bash
    set -e ;
    
    issuer_file=$1
    namespace=gitlab
    
    echo "Creating the certmanager issuer..."
    set +e ; # The CRD may not exist yet. We need to retry until this passes
    while ! kubectl --namespace=$namespace apply -f ${issuer_file:=issuer.yml}; do
      sleep 1;
    done ;
    set -e ; # reset `e` as active
    
  issuer.yml: |
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: gitlab-selfsigned-issuer
    spec:
      selfSigned: {}
    ---
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: gitlab-selfsigned-ca
      namespace: gitlab
    spec:
      isCA: true
      commonName: dev.local
      secretName: gitlab-ca-secret
      privateKey:
        algorithm: ECDSA
        size: 256
      issuerRef:
        name: gitlab-selfsigned-issuer
        kind: ClusterIssuer
        group: cert-manager.io
    ---
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: gitlab-issuer
      namespace: gitlab
      labels:
        app: certmanager-issuer
        chart: certmanager-issuer-0.1.0
        release: gitlab
        heritage: Helm
    spec:
      ca:
        secretName: gitlab-ca-secret
      #   acme:
        # The ACME server URL
        #  server: "https://acme-v02.api.letsencrypt.org/directory"
        # Email address used for ACME registration
        #email: "me@dev.local.com"
        # Name of a secret used to store the ACME account private key
        #privateKeySecretRef:
        #  name: gitlab-acme-key
        # Enable the HTTP-01 challenge provider
        #solvers:
        #- selector: {}
        #  http01:
        #    ingress:
        #      class: gitlab-nginx
