---
# Source: gitlab/charts/certmanager-issuer/templates/issuer-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: gitlab-issuer-1
  namespace: gitlab
  labels:
    app: certmanager-issuer
    chart: certmanager-issuer-0.1.0
    release: gitlab
    heritage: Helm
    
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: certmanager-issuer
        release: gitlab
    spec:
      
      securityContext:
        runAsUser: 65534
        fsGroup: 65534
      serviceAccountName: gitlab-certmanager-issuer
      restartPolicy: OnFailure      
      
      containers:
        - name: create-issuer
          image: "registry.gitlab.com/gitlab-org/build/cng/kubectl:1.18.20@sha256:8d27c191af306cafddba2f293c5613f8966363f779d79a5599ad0231e60069e4"
          command: ['/bin/bash', '/scripts/create-issuer', '/scripts/issuer.yml']          
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          resources:
            requests:
              cpu: 50m
      volumes:
      - name: scripts
        configMap:
          name: gitlab-certmanager-issuer-certmanager
