apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kap-apiserver-exporter
  namespace: monitoring
  labels:
    app: kap-apiserver
    app.kubernetes.io/name: kap-apiserver
    prometheus: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: https
    scheme: https
    metricRelabelings:
    - sourceLabels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_name
        - __meta_kubernetes_endpoint_port_name
      action: keep
      regex: default;kubernetes;https
    - targetLabel: __address__
      replacement: kubernetes.default.svc:443
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      serverName: kubernetes
      insecureSkipVerify: false
  jobLabel: component
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      component: apiserver
      provider: kubernetes