apiVersion: v1
kind: Endpoints
metadata:
  name: kap-kube-controller-manager
  labels:
    app: kap-kube-controller-manager
    k8s-app: kube-controller-manager
  namespace: kube-system
subsets:
- addresses:
  - 
---
apiVersion: v1
kind: Service
metadata:
  name: kap-kube-controller-manager
  labels:
    app: kap-kube-controller-manager
    jobLabel: kube-controller-manager
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 