apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
commonLabels:
  app.kubernetes.io/name: external-dns
  app.kubernetes.io/part-of: external-dns
resources:
- namespace.yml
- etcd/
- external-dns/rbac/rbac.yml
- external-dns/
