apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab
commonLabels:
  app.kubernetes.io/name: registry
  app.kubernetes.io/part-of: gitlab
resources:
- configmap.yaml
- deployment.yaml
- hpa.yaml
- ingress.yaml
- pdb.yaml
- service.yaml
