apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-postgresql-init-db
  namespace: sonarqube
  labels:
    app: sonarqube
    release: sonarqube
data:
  init_revision.sh: |
    if [[ ! -f "$POSTGRESQL_VOLUME_DIR/.sonarqube_1_scripts_initialized" ]] ; then
      rm -f "$POSTGRESQL_VOLUME_DIR/.user_scripts_initialized"
      touch "$POSTGRESQL_VOLUME_DIR/.sonarqube_1_scripts_initialized"
    fi