apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sonarqube
commonLabels:
  app.kubernetes.io/name: postgresql
  app.kubernetes.io/part-of: sonarqube
resources:
- secret.yml
- configmap.yml
- statefulset.yml
- service.yml