---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-postgresql-headless
  namespace: sonarqube
  labels:
    app: postgresql
    release: sonarqube
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app: postgresql
    release: sonarqube
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-postgresql
  namespace: sonarqube
  labels:
    app: postgresql
    release: sonarqube
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app: postgresql
    release: sonarqube
    role: master